ALTER TABLE coopdata ADD CONSTRAINT check(time is not null)
ALTER TABLE coopdata ADD CONSTRAINT check(high_F is not null)
ALTER TABLE coopdata ADD CONSTRAINT check(low_F is not null)
ALTER TABLE coopdata ADD CONSTRAINT check(-100<high_F<=212)
ALTER TABLE coopdata ADD CONSTRAINT check(-100<low_F<=212)
ALTER TABLE coopdata MODIFY nwsli varchar(10)
ALTER TABLE coopdata MODIFY `date` varchar(20)
ALTER TABLE coopdata ADD primary key(nwsli, `date`)
ALTER TABLE coopmetadata MODIFY id varchar(10)
ALTER table coopmetadata ADD CONSTRAINT check(Longitude1 is not null)
ALTER table coopmetadata ADD CONSTRAINT check(Latitude1 is not null)
ALTER TABLE coopmetadata ADD primary key(id)
ALTER TABLE asosdata ADD CONSTRAINT check(tmpf is not null)
ALTER TABLE asosdata ADD CONSTRAINT check(relh is not null)
ALTER TABLE asosdata ADD CONSTRAINT check(feel is not null)
ALTER TABLE asosdata ADD CONSTRAINT check(sped is not null)
ALTER TABLE asosdata ADD CONSTRAINT check(-100<tmpf<=212)
ALTER TABLE asosdata ADD CONSTRAINT check(0<=relh<=100)
ALTER TABLE asosdata ADD CONSTRAINT check(-100<feel<=212)
ALTER TABLE asosdata ADD CONSTRAINT check(0<=sped<=100)
ALTER TABLE asosdata MODIFY station varchar(10)
ALTER TABLE asosdata MODIFY valid varchar(20)
ALTER TABLE asosdata ADD primary key(station, valid)
ALTER table asosmetadata MODIFY station varchar(10)
ALTER table asosmetadata ADD CONSTRAINT check(lon is not null)
ALTER table asosmetadata ADD CONSTRAINT check(lat is not null)
ALTER table asosmetadata ADD primary key(station)
